openapi: 3.0.0

info:
  version: "2.0"
  title: Employees API
  description: API to work with employee domain
  x-papi-gateway:
    service-url: http://employees-data-service

servers:
  - url: https://api.personio.de

paths:
  /employees:
    get:
      security:
        - OAuth2:
            - employees:read
      tags:
        - Employees
      description: 'List of employees'
    post:
      security:
        - OAuth2:
            - employees:write
      tags:
        - Employees
      description: 'Create new employee'
  /employees/{employee_id}:
    get:
      security:
        - OAuth2:
            - employees:read
      tags:
        - Employees
      description: 'Show employee'
    patch:
      security:
        - OAuth2:
            - employees:write
      tags:
        - Employees
      description: 'Patch employee'
    delete:
      security:
        - OAuth2:
            - employees:write
      tags:
        - Employees
      description: 'Delete employee'
components:
  # Responses ============================================================================
  # Security ============================================================================
  securitySchemes:
    OAuth2:
      type: oauth2openapi: 3.0.0

info:
  version: "2.0"
  title: Employees API
  description: API to work with employee domain
  x-papi-gateway:
    service-url: http://employees-data-service

servers:
  - url: https://api.personio.de

paths:
  /employees:
    get:
      security:
        - OAuth2:
            - employees:read
      tags:
        - Employees
      description: 'List of employees'
    post:
      security:
        - OAuth2:
            - employees:write
      tags:
        - Employees
      description: 'Create new employee'
  /employees/{employee_id}:
    get:
      security:
        - OAuth2:
            - employees:read
      tags:
        - Employees
      description: 'Show employee'
    patch:
      security:
        - OAuth2:
            - employees:write
      tags:
        - Employees
      description: 'Patch employee'
    delete:
      security:
        - OAuth2:
            - employees:write
      tags:
        - Employees
      description: 'Delete employee'
components:
  # Responses ============================================================================
  # Security ============================================================================
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://api.persoio.de/v2/auth/token
          scopes:
            employees:read: Grants read access
            employees:write: Grants write access

      flows:
        clientCredentials:
          tokenUrl: https://api.persoio.de/v2/auth/token
          scopes:
            employees:read: Grants read access
            employees:write: Grants write access
